
from PyQt5 import QtCore, QtGui, QtWidgets

from UI.UserType import UserType
from UI.authorUploadAbstractUi import uploadAbstractUi
from UI.PCMemberUi import Ui_PCMember

class Ui_MainWindow(object):
    def openPCMemberUi(self):
        self.window = QtWidgets.QStackedWidget()
        self.ui = Ui_PCMember()
        self.ui.setupUi(self.window, self.user)
        self.window.show()

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = uploadAbstractUi()
        self.ui.setupUi(self.window)
        self.window.show()

    def setUser(self, user: UserType):
        self.user = user
        if self.user.isOnlyAuthor == True:  ##Is only author
            self.manageConferenceBtn.setEnabled(False)



    def setupUi(self, authorMainWindow, user):
        authorMainWindow.setObjectName("authorMainWindow")
        authorMainWindow.resize(1024, 720)
        self.centralwidget = QtWidgets.QWidget(authorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.myDocumentsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.myDocumentsBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myDocumentsBtn.sizePolicy().hasHeightForWidth())
        self.myDocumentsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.myDocumentsBtn.setFont(font)
        self.myDocumentsBtn.setObjectName("myDocumentsBtn")
        self.verticalLayout.addWidget(self.myDocumentsBtn)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(300, 150, 441, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.currentAbstractList = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.currentAbstractList.setObjectName("currentAbstractList")
        self.gridLayout.addWidget(self.currentAbstractList, 0, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 490, 281, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.manageConferenceBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.manageConferenceBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manageConferenceBtn.sizePolicy().hasHeightForWidth())
        self.manageConferenceBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.manageConferenceBtn.setFont(font)
        self.manageConferenceBtn.setObjectName("manageConferenceBtn")
        self.verticalLayout_5.addWidget(self.manageConferenceBtn)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(310, 10, 281, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.uploadAbstractBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.uploadAbstractBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadAbstractBtn.sizePolicy().hasHeightForWidth())
        self.uploadAbstractBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.uploadAbstractBtn.setFont(font)
        self.uploadAbstractBtn.setObjectName("uploadAbstractBtn")

        self.verticalLayout_7.addWidget(self.uploadAbstractBtn)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(620, 10, 281, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.uploadDocumentBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.uploadDocumentBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadDocumentBtn.sizePolicy().hasHeightForWidth())
        self.uploadDocumentBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.uploadDocumentBtn.setFont(font)
        self.uploadDocumentBtn.setObjectName("uploadDocumentBtn")
        self.verticalLayout_8.addWidget(self.uploadDocumentBtn)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(300, 100, 441, 43))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(749, 149, 271, 431))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.paperStatusList = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.paperStatusList.setObjectName("paperStatusList")
        self.gridLayout_2.addWidget(self.paperStatusList, 0, 0, 1, 1)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(750, 100, 251, 41))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        authorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(authorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        authorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(authorMainWindow)
        self.statusbar.setObjectName("statusbar")
        authorMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(authorMainWindow)
        #Open upload abstract UI
        self.uploadAbstractBtn.clicked.connect(self.openWindow)  #######
        #Open Pc Member UI
        self.manageConferenceBtn.clicked.connect(self.openPCMemberUi)
        self.manageConferenceBtn.clicked.connect(authorMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(authorMainWindow)
        ### SET USER
        self.setUser(user)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Author"))
        self.myDocumentsBtn.setText(_translate("MainWindow", "My Documents"))
        self.manageConferenceBtn.setText(_translate("MainWindow", "Manage Conference"))
        self.uploadAbstractBtn.setText(_translate("MainWindow", "Upload Abstract"))
        self.uploadDocumentBtn.setText(_translate("MainWindow", "Upload Document"))
        self.label.setText(_translate("MainWindow", "Current Abstract"))
        self.label_3.setText(_translate("MainWindow", "Paper Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, UserType(False, True, False, 'user1'))
    MainWindow.show()
    sys.exit(app.exec_())
