
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QListWidgetItem

from UI.ReviewingProcessPopUp import Ui_ReviewingProcessPopUp
from UI.ReviewerReviews import Ui_ReviewerReviews
from UI.UserType import UserType
from UI.service import Service


class Ui_PCMember(object):
    def openReviewingProcessPopUp(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ReviewingProcessPopUp()
        self.ui.setupUi(self.window)
        self.window.show()

    def openAuthorWindow(self):
        from UI.authorUi import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window, self.user)
        self.window.show()

    def openReviewerReviews(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ReviewerReviews()
        self.ui.setupUi(self.window)
        self.window.show()

    def setUser(self, user: UserType):
        self.user = user


    def showPaperContent(self):
        row = self.papersToBidList.selectedIndexes()[0].data(1)
        self.paperTextEdit.setText(str(row))

    def submitPaperBid(self):
        try:
            row = self.papersToBidList.selectedIndexes()[0].data(1)
            try:
                grade = int(self.gradeLineEdit.text())
                if grade <= 7 and grade >= 1:
                    Service().paperListSubmitBidCheck(grade, row.paperID)
                else:
                    self.bidding_ErrorMessageLabel.setText('Invalid Grade, 1 <= grade <= 7')
            except:
                self.bidding_ErrorMessageLabel.setText('Invalid Grade, 1 <= grade <= 7')
        except:
            self.bidding_ErrorMessageLabel.setText('Please select a paper')


    def setupUi(self, PCMember, user):
        ###SET USER
        self.setUser(user)
        PCMember.setObjectName("PCMember")
        PCMember.resize(1024, 720)
        ### BIDING ###
        self.Biding = QtWidgets.QWidget()
        self.Biding.setObjectName("Biding")
        self.submitBtn = QtWidgets.QPushButton(self.Biding)
        self.submitBtn.setGeometry(QtCore.QRect(820, 600, 141, 41))
        self.submitBtn.setObjectName("submitBtn")
        self.papersToBidList = QtWidgets.QListWidget(self.Biding)
        self.papersToBidList.setGeometry(QtCore.QRect(210, 60, 256, 560))
        self.papersToBidList.setObjectName("papersToBidList")
        self.label_2 = QtWidgets.QLabel(self.Biding)#PAPER TEXT
        self.label_2.setGeometry(QtCore.QRect(480, 30, 100, 30))#PAPER TEXT
        self.label_2.setObjectName("label_2")#PAPER TEXT
        self.label = QtWidgets.QLabel(self.Biding)#PAPER LIST
        self.label.setGeometry(QtCore.QRect(210, 30, 100, 30))#PAPER LIST
        self.label.setObjectName("label")#PAPER LIST
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Biding)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(5, 20, 180, 649))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.buttonsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.biding_bidingBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_bidingBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.biding_bidingBtn.sizePolicy().hasHeightForWidth())
        self.biding_bidingBtn.setSizePolicy(sizePolicy)
        self.biding_bidingBtn.setMaximumSize(QtCore.QSize(400, 50))
        self.biding_bidingBtn.setObjectName("biding_bidingBtn")
        self.buttonsLayout.addWidget(self.biding_bidingBtn)
        self.biding_assignReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_assignReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.biding_assignReviewsBtn.setObjectName("biding_assignReviewsBtn")
        self.buttonsLayout.addWidget(self.biding_assignReviewsBtn)
        self.biding_nonConclusiveReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_nonConclusiveReviewsBtn.setEnabled(True)
        self.biding_nonConclusiveReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.biding_nonConclusiveReviewsBtn.setObjectName("biding_nonConclusiveReviewsBtn")
        self.buttonsLayout.addWidget(self.biding_nonConclusiveReviewsBtn)
        self.biding_changeDeadlinesBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_changeDeadlinesBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.biding_changeDeadlinesBtn.setObjectName("biding_changeDeadlinesBtn")
        self.buttonsLayout.addWidget(self.biding_changeDeadlinesBtn)
        self.biding_chooseSectionToSuperviseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_chooseSectionToSuperviseBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.biding_chooseSectionToSuperviseBtn.setObjectName("biding_chooseSectionToSuperviseBtn")
        self.buttonsLayout.addWidget(self.biding_chooseSectionToSuperviseBtn)
        self.biding_viewAssignedPapersBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_viewAssignedPapersBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.biding_viewAssignedPapersBtn.setObjectName("biding_viewAssignedPapersBtn")
        self.buttonsLayout.addWidget(self.biding_viewAssignedPapersBtn)
        self.biding_viewYourPaperBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.biding_viewYourPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.biding_viewYourPaperBtn.setObjectName("biding_viewYourPaperBtn")
        self.buttonsLayout.addWidget(self.biding_viewYourPaperBtn)
        self.paperTextEdit = QtWidgets.QTextEdit(self.Biding)
        self.paperTextEdit.setGeometry(QtCore.QRect(480, 60, 531, 521))
        self.paperTextEdit.setObjectName("paperTextEdit")
        self.paperTextEdit.setReadOnly(True)
        self.gradeLineEdit = QtWidgets.QLineEdit(self.Biding)
        self.gradeLineEdit.setGeometry(QtCore.QRect(520, 610, 280, 30))
        self.gradeLineEdit.setObjectName("gradeLineEdit")
        self.bidding_ErrorMessageLabel = QtWidgets.QLabel(self.Biding)
        self.bidding_ErrorMessageLabel.setGeometry(QtCore.QRect(520, 660, 231, 30))
        self.bidding_ErrorMessageLabel.setObjectName("ErrorMessage")
        PCMember.addWidget(self.Biding)
        ### ASSIGN REVIEWS ###
        self.AssignReviews = QtWidgets.QWidget()
        self.AssignReviews.setObjectName("AssignReviews")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.AssignReviews)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(5, 20, 180, 649))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.buttonsLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.buttonsLayout_2.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout_2.setObjectName("buttonsLayout_2")
        self.assignReviews_bidingBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_bidingBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assignReviews_bidingBtn.sizePolicy().hasHeightForWidth())
        self.assignReviews_bidingBtn.setSizePolicy(sizePolicy)
        self.assignReviews_bidingBtn.setMaximumSize(QtCore.QSize(400, 50))
        self.assignReviews_bidingBtn.setObjectName("assignReviews_bidingBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_bidingBtn)
        self.assignReviews_assignReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_assignReviewsBtn.setEnabled(False)
        self.assignReviews_assignReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignReviews_assignReviewsBtn.setObjectName("assignReviews_assignReviewsBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_assignReviewsBtn)
        self.assignReviews_nonConclusiveReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_nonConclusiveReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignReviews_nonConclusiveReviewsBtn.setObjectName("assignReviews_nonConclusiveReviewsBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_nonConclusiveReviewsBtn)
        self.assignReviews_changeDeadlinesBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_changeDeadlinesBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignReviews_changeDeadlinesBtn.setObjectName("assignReviews_changeDeadlinesBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_changeDeadlinesBtn)
        self.assignReviews_chooseSectionToSuperviseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_chooseSectionToSuperviseBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignReviews_chooseSectionToSuperviseBtn.setObjectName("assignReviews_chooseSectionToSuperviseBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_chooseSectionToSuperviseBtn)
        self.assignReviews_viewAssignedPapersBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_viewAssignedPapersBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignReviews_viewAssignedPapersBtn.setObjectName("assignReviews_viewAssignedPapersBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_viewAssignedPapersBtn)
        self.assignReviews_viewYourPaperBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.assignReviews_viewYourPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignReviews_viewYourPaperBtn.setObjectName("assignReviews_viewYourPaperBtn")
        self.buttonsLayout_2.addWidget(self.assignReviews_viewYourPaperBtn)
        self.clearBtn = QtWidgets.QPushButton(self.AssignReviews)
        self.clearBtn.setGeometry(QtCore.QRect(850, 380, 121, 51))
        self.clearBtn.setObjectName("clearBtn")
        self.viewReviewingProcessBtn = QtWidgets.QPushButton(self.AssignReviews)
        self.viewReviewingProcessBtn.setGeometry(QtCore.QRect(730, 490, 210, 71))
        self.viewReviewingProcessBtn.setObjectName("viewReviewingProcessBtn")
        self.assignPaperBtn = QtWidgets.QPushButton(self.AssignReviews)
        self.assignPaperBtn.setGeometry(QtCore.QRect(690, 380, 121, 50))
        self.assignPaperBtn.setObjectName("assignPaperBtn")
        self.selectedReviewersList = QtWidgets.QListWidget(self.AssignReviews)
        self.selectedReviewersList.setGeometry(QtCore.QRect(670, 20, 319, 319))
        self.selectedReviewersList.setObjectName("selectedReviewersList")
        self.availableReviewersList = QtWidgets.QListWidget(self.AssignReviews)
        self.availableReviewersList.setGeometry(QtCore.QRect(430, 20, 229, 649))
        self.availableReviewersList.setObjectName("availableReviewersList")
        self.papersList = QtWidgets.QListWidget(self.AssignReviews)
        self.papersList.setGeometry(QtCore.QRect(190, 20, 229, 649))
        self.papersList.setObjectName("papersList")
        PCMember.addWidget(self.AssignReviews)
        ### NON CONCLUSIVE REVIEWS ###
        self.NonConclusiveReviews = QtWidgets.QWidget()
        self.NonConclusiveReviews.setObjectName("NonConclusiveReviews")
        self.requestReconsiderationBtn = QtWidgets.QPushButton(self.NonConclusiveReviews)
        self.requestReconsiderationBtn.setGeometry(QtCore.QRect(580, 610, 178, 50))
        self.requestReconsiderationBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.requestReconsiderationBtn.setObjectName("requestReconsiderationBtn")
        self.label_3 = QtWidgets.QLabel(self.NonConclusiveReviews)
        self.label_3.setGeometry(QtCore.QRect(420, 20, 90, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.NonConclusiveReviews)
        self.label_4.setGeometry(QtCore.QRect(200, 20, 60, 16))
        self.label_4.setObjectName("label_4")
        self.assignNewReviewerBtn = QtWidgets.QPushButton(self.NonConclusiveReviews)
        self.assignNewReviewerBtn.setGeometry(QtCore.QRect(200, 610, 178, 50))
        self.assignNewReviewerBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assignNewReviewerBtn.setObjectName("assignNewReviewerBtn")
        self.label_5 = QtWidgets.QLabel(self.NonConclusiveReviews)
        self.label_5.setGeometry(QtCore.QRect(640, 20, 120, 16))
        self.label_5.setObjectName("label_5")
        self.acceptPaperBtn = QtWidgets.QPushButton(self.NonConclusiveReviews)
        self.acceptPaperBtn.setGeometry(QtCore.QRect(200, 550, 178, 50))
        self.acceptPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.acceptPaperBtn.setObjectName("acceptPaperBtn")
        self.paperList = QtWidgets.QListWidget(self.NonConclusiveReviews)
        self.paperList.setGeometry(QtCore.QRect(190, 40, 211, 491))
        self.paperList.setObjectName("paperList")
        self.paperContent = QtWidgets.QTextEdit(self.NonConclusiveReviews)
        self.paperContent.setGeometry(QtCore.QRect(630, 40, 390, 491))
        self.paperContent.setObjectName("paperContent")
        self.rejectPaperBtn = QtWidgets.QPushButton(self.NonConclusiveReviews)
        self.rejectPaperBtn.setGeometry(QtCore.QRect(390, 550, 178, 50))
        self.rejectPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.rejectPaperBtn.setObjectName("rejectPaperBtn")
        self.addReviewerBtn = QtWidgets.QPushButton(self.NonConclusiveReviews)
        self.addReviewerBtn.setGeometry(QtCore.QRect(390, 610, 178, 50))
        self.addReviewerBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.addReviewerBtn.setObjectName("addReviewerBtn")
        self.reviewersList = QtWidgets.QListWidget(self.NonConclusiveReviews)
        self.reviewersList.setGeometry(QtCore.QRect(410, 40, 211, 491))
        self.reviewersList.setObjectName("reviewersList")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.NonConclusiveReviews)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(5, 20, 180, 649))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.buttonsLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.buttonsLayout_3.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout_3.setObjectName("buttonsLayout_3")
        self.nonConclusive_bidingBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_bidingBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonConclusive_bidingBtn.sizePolicy().hasHeightForWidth())
        self.nonConclusive_bidingBtn.setSizePolicy(sizePolicy)
        self.nonConclusive_bidingBtn.setMaximumSize(QtCore.QSize(400, 50))
        self.nonConclusive_bidingBtn.setObjectName("nonConclusive_bidingBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_bidingBtn)
        self.nonConclusive_assignReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_assignReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.nonConclusive_assignReviewsBtn.setObjectName("nonConclusive_assignReviewsBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_assignReviewsBtn)
        self.nonConclusive_nonConclusiveReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_nonConclusiveReviewsBtn.setEnabled(False)
        self.nonConclusive_nonConclusiveReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.nonConclusive_nonConclusiveReviewsBtn.setObjectName("nonConclusive_nonConclusiveReviewsBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_nonConclusiveReviewsBtn)
        self.nonConclusive_changeDeadlinesBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_changeDeadlinesBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.nonConclusive_changeDeadlinesBtn.setObjectName("nonConclusive_changeDeadlinesBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_changeDeadlinesBtn)
        self.nonConclusive_chooseSectionToSuperviseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_chooseSectionToSuperviseBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.nonConclusive_chooseSectionToSuperviseBtn.setObjectName("nonConclusive_chooseSectionToSuperviseBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_chooseSectionToSuperviseBtn)
        self.nonConclusive_viewAssignedPapersBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_viewAssignedPapersBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.nonConclusive_viewAssignedPapersBtn.setObjectName("nonConclusive_viewAssignedPapersBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_viewAssignedPapersBtn)
        self.nonConclusive_viewYourPaperBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nonConclusive_viewYourPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.nonConclusive_viewYourPaperBtn.setObjectName("nonConclusive_viewYourPaperBtn")
        self.buttonsLayout_3.addWidget(self.nonConclusive_viewYourPaperBtn)
        PCMember.addWidget(self.NonConclusiveReviews)
        ### CHANGE DEADLINE ###
        self.ChangeDeadlines = QtWidgets.QWidget()
        self.ChangeDeadlines.setObjectName("ChangeDeadlines")
        self.listView = QtWidgets.QListView(self.ChangeDeadlines)
        self.listView.setGeometry(QtCore.QRect(410, 30, 290, 30))
        self.listView.setObjectName("listView")
        self.label_6 = QtWidgets.QLabel(self.ChangeDeadlines)
        self.label_6.setGeometry(QtCore.QRect(220, 180, 170, 30))
        self.label_6.setObjectName("label_6")
        self.updateConfirmationLabel = QtWidgets.QLabel(self.ChangeDeadlines)
        self.updateConfirmationLabel.setGeometry(QtCore.QRect(390, 270, 180, 40))
        self.updateConfirmationLabel.setObjectName("updateConfirmationLabel")
        self.pushButton = QtWidgets.QPushButton(self.ChangeDeadlines)
        self.pushButton.setGeometry(QtCore.QRect(220, 260, 151, 61))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.ChangeDeadlines)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(5, 20, 180, 649))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.buttonsLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.buttonsLayout_4.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout_4.setObjectName("buttonsLayout_4")
        self.changeDeadlines_bidingBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_bidingBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changeDeadlines_bidingBtn.sizePolicy().hasHeightForWidth())
        self.changeDeadlines_bidingBtn.setSizePolicy(sizePolicy)
        self.changeDeadlines_bidingBtn.setMaximumSize(QtCore.QSize(400, 50))
        self.changeDeadlines_bidingBtn.setObjectName("changeDeadlines_bidingBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_bidingBtn)
        self.changeDeadlines_assignReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_assignReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changeDeadlines_assignReviewsBtn.setObjectName("changeDeadlines_assignReviewsBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_assignReviewsBtn)
        self.changeDeadlines_nonConclusiveReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_nonConclusiveReviewsBtn.setEnabled(True)
        self.changeDeadlines_nonConclusiveReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changeDeadlines_nonConclusiveReviewsBtn.setObjectName("changeDeadlines_nonConclusiveReviewsBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_nonConclusiveReviewsBtn)
        self.changeDeadlines_changeDeadlinesBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_changeDeadlinesBtn.setEnabled(False)
        self.changeDeadlines_changeDeadlinesBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changeDeadlines_changeDeadlinesBtn.setObjectName("changeDeadlines_changeDeadlinesBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_changeDeadlinesBtn)
        self.changeDeadlines_chooseSectionToSuperviseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_chooseSectionToSuperviseBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changeDeadlines_chooseSectionToSuperviseBtn.setObjectName("changeDeadlines_chooseSectionToSuperviseBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_chooseSectionToSuperviseBtn)
        self.changeDeadlines_viewAssignedPapersBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_viewAssignedPapersBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changeDeadlines_viewAssignedPapersBtn.setObjectName("changeDeadlines_viewAssignedPapersBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_viewAssignedPapersBtn)
        self.changeDeadlines_viewYourPaperBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.changeDeadlines_viewYourPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.changeDeadlines_viewYourPaperBtn.setObjectName("changeDeadlines_viewYourPaperBtn")
        self.buttonsLayout_4.addWidget(self.changeDeadlines_viewYourPaperBtn)
        self.label_7 = QtWidgets.QLabel(self.ChangeDeadlines)
        self.label_7.setGeometry(QtCore.QRect(220, 130, 170, 30))
        self.label_7.setObjectName("label_7")
        self.listView_2 = QtWidgets.QListView(self.ChangeDeadlines)
        self.listView_2.setGeometry(QtCore.QRect(410, 80, 290, 30))
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(self.ChangeDeadlines)
        self.listView_3.setGeometry(QtCore.QRect(410, 130, 290, 30))
        self.listView_3.setObjectName("listView_3")
        self.label_8 = QtWidgets.QLabel(self.ChangeDeadlines)
        self.label_8.setGeometry(QtCore.QRect(220, 80, 170, 30))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.ChangeDeadlines)
        self.label_9.setGeometry(QtCore.QRect(220, 30, 170, 30))
        self.label_9.setObjectName("label_9")
        self.listView_4 = QtWidgets.QListView(self.ChangeDeadlines)
        self.listView_4.setGeometry(QtCore.QRect(410, 180, 290, 30))
        self.listView_4.setObjectName("listView_4")
        PCMember.addWidget(self.ChangeDeadlines)
        ### SECTION TO SUPERVISE ###
        self.SectionToSupervise = QtWidgets.QWidget()
        self.SectionToSupervise.setObjectName("SectionToSupervise")
        self.updateBtn = QtWidgets.QPushButton(self.SectionToSupervise)
        self.updateBtn.setGeometry(QtCore.QRect(240, 570, 171, 51))
        self.updateBtn.setObjectName("updateBtn")
        self.tableWidget = QtWidgets.QTableWidget(self.SectionToSupervise)
        self.tableWidget.setGeometry(QtCore.QRect(230, 80, 781, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.SectionToSupervise)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(5, 20, 180, 649))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.buttonsLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.buttonsLayout_5.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout_5.setObjectName("buttonsLayout_5")
        self.sectionToSupervise_bidingBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_bidingBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionToSupervise_bidingBtn.sizePolicy().hasHeightForWidth())
        self.sectionToSupervise_bidingBtn.setSizePolicy(sizePolicy)
        self.sectionToSupervise_bidingBtn.setMaximumSize(QtCore.QSize(400, 50))
        self.sectionToSupervise_bidingBtn.setObjectName("sectionToSupervise_bidingBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_bidingBtn)
        self.sectionToSupervise_assignReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_assignReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sectionToSupervise_assignReviewsBtn.setObjectName("sectionToSupervise_assignReviewsBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_assignReviewsBtn)
        self.sectionToSupervise_nonConclusiveReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_nonConclusiveReviewsBtn.setEnabled(True)
        self.sectionToSupervise_nonConclusiveReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sectionToSupervise_nonConclusiveReviewsBtn.setObjectName("sectionToSupervise_nonConclusiveReviewsBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_nonConclusiveReviewsBtn)
        self.sectionToSupervise_changeDeadlinesBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_changeDeadlinesBtn.setEnabled(True)
        self.sectionToSupervise_changeDeadlinesBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sectionToSupervise_changeDeadlinesBtn.setObjectName("sectionToSupervise_changeDeadlinesBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_changeDeadlinesBtn)
        self.sectionToSupervise_chooseSectionToSuperviseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_chooseSectionToSuperviseBtn.setEnabled(False)
        self.sectionToSupervise_chooseSectionToSuperviseBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sectionToSupervise_chooseSectionToSuperviseBtn.setObjectName("sectionToSupervise_chooseSectionToSuperviseBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_chooseSectionToSuperviseBtn)
        self.sectionToSupervise_viewAssignedPapersBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_viewAssignedPapersBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sectionToSupervise_viewAssignedPapersBtn.setObjectName("sectionToSupervise_viewAssignedPapersBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_viewAssignedPapersBtn)
        self.sectionToSupervise_viewYourPaperBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.sectionToSupervise_viewYourPaperBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sectionToSupervise_viewYourPaperBtn.setObjectName("sectionToSupervise_viewYourPaperBtn")
        self.buttonsLayout_5.addWidget(self.sectionToSupervise_viewYourPaperBtn)
        PCMember.addWidget(self.SectionToSupervise)
        self.Biding.resize(1024, 720)
        self.AssignReviews.resize(1024, 720)
        self.NonConclusiveReviews.resize(1024, 720)
        self.ChangeDeadlines.resize(1024, 720)
        self.SectionToSupervise.resize(1024, 720)

        self.retranslateUi(PCMember)
        PCMember.setCurrentIndex(0)
        self.biding_assignReviewsBtn.clicked.connect(self.Biding.hide)
        self.biding_assignReviewsBtn.clicked.connect(self.AssignReviews.show)
        self.biding_nonConclusiveReviewsBtn.clicked.connect(self.Biding.hide)
        self.biding_nonConclusiveReviewsBtn.clicked.connect(self.NonConclusiveReviews.show)
        self.biding_changeDeadlinesBtn.clicked.connect(self.Biding.hide)
        self.biding_changeDeadlinesBtn.clicked.connect(self.ChangeDeadlines.show)
        self.biding_chooseSectionToSuperviseBtn.clicked.connect(self.Biding.hide)
        self.biding_chooseSectionToSuperviseBtn.clicked.connect(self.SectionToSupervise.show)
        self.assignReviews_bidingBtn.clicked.connect(self.AssignReviews.hide)
        self.assignReviews_bidingBtn.clicked.connect(self.Biding.show)
        self.assignReviews_nonConclusiveReviewsBtn.clicked.connect(self.AssignReviews.hide)
        self.assignReviews_nonConclusiveReviewsBtn.clicked.connect(self.NonConclusiveReviews.show)
        self.assignReviews_changeDeadlinesBtn.clicked.connect(self.AssignReviews.hide)
        self.assignReviews_changeDeadlinesBtn.clicked.connect(self.ChangeDeadlines.show)
        self.assignReviews_chooseSectionToSuperviseBtn.clicked.connect(self.AssignReviews.hide)
        self.assignReviews_chooseSectionToSuperviseBtn.clicked.connect(self.SectionToSupervise.show)
        self.nonConclusive_assignReviewsBtn.clicked.connect(self.AssignReviews.show)
        self.nonConclusive_assignReviewsBtn.clicked.connect(self.NonConclusiveReviews.hide)
        self.nonConclusive_bidingBtn.clicked.connect(self.NonConclusiveReviews.hide)
        self.nonConclusive_bidingBtn.clicked.connect(self.Biding.show)
        self.nonConclusive_changeDeadlinesBtn.clicked.connect(self.NonConclusiveReviews.hide)
        self.nonConclusive_changeDeadlinesBtn.clicked.connect(self.ChangeDeadlines.show)
        self.nonConclusive_chooseSectionToSuperviseBtn.clicked.connect(self.NonConclusiveReviews.hide)
        self.nonConclusive_chooseSectionToSuperviseBtn.clicked.connect(self.SectionToSupervise.show)
        self.changeDeadlines_assignReviewsBtn.clicked.connect(self.ChangeDeadlines.hide)
        self.changeDeadlines_assignReviewsBtn.clicked.connect(self.AssignReviews.show)
        self.changeDeadlines_bidingBtn.clicked.connect(self.ChangeDeadlines.hide)
        self.changeDeadlines_bidingBtn.clicked.connect(self.Biding.show)
        self.changeDeadlines_chooseSectionToSuperviseBtn.clicked.connect(self.ChangeDeadlines.hide)
        self.changeDeadlines_chooseSectionToSuperviseBtn.clicked.connect(self.SectionToSupervise.show)
        self.changeDeadlines_nonConclusiveReviewsBtn.clicked.connect(self.ChangeDeadlines.hide)
        self.changeDeadlines_nonConclusiveReviewsBtn.clicked.connect(self.NonConclusiveReviews.show)
        self.sectionToSupervise_assignReviewsBtn.clicked.connect(self.SectionToSupervise.hide)
        self.sectionToSupervise_assignReviewsBtn.clicked.connect(self.AssignReviews.show)
        self.sectionToSupervise_bidingBtn.clicked.connect(self.SectionToSupervise.hide)
        self.sectionToSupervise_bidingBtn.clicked.connect(self.Biding.show)
        self.sectionToSupervise_changeDeadlinesBtn.clicked.connect(self.SectionToSupervise.hide)
        self.sectionToSupervise_changeDeadlinesBtn.clicked.connect(self.ChangeDeadlines.show)
        self.sectionToSupervise_nonConclusiveReviewsBtn.clicked.connect(self.SectionToSupervise.hide)
        self.sectionToSupervise_nonConclusiveReviewsBtn.clicked.connect(self.NonConclusiveReviews.show)


        ###GO TO REVIEWER REVIEWS PAGE
        self.biding_viewAssignedPapersBtn.clicked.connect(self.openReviewerReviews)
        self.assignReviews_viewAssignedPapersBtn.clicked.connect(self.openReviewerReviews)
        self.nonConclusive_viewAssignedPapersBtn.clicked.connect(self.openReviewerReviews)
        self.changeDeadlines_viewAssignedPapersBtn.clicked.connect(self.openReviewerReviews)
        self.sectionToSupervise_viewAssignedPapersBtn.clicked.connect(self.openReviewerReviews)
        ###

        ###GO TO AUTHOR PAGE
        self.biding_viewYourPaperBtn.clicked.connect(self.openAuthorWindow)
        self.biding_viewYourPaperBtn.clicked.connect(PCMember.close)
        self.assignReviews_viewYourPaperBtn.clicked.connect(self.openAuthorWindow)
        self.assignReviews_viewYourPaperBtn.clicked.connect(PCMember.close)
        self.nonConclusive_viewYourPaperBtn.clicked.connect(self.openAuthorWindow)
        self.nonConclusive_viewYourPaperBtn.clicked.connect(PCMember.close)
        self.changeDeadlines_viewYourPaperBtn.clicked.connect(self.openAuthorWindow)
        self.changeDeadlines_viewYourPaperBtn.clicked.connect(PCMember.close)
        self.sectionToSupervise_viewYourPaperBtn.clicked.connect(self.openAuthorWindow)
        self.sectionToSupervise_viewYourPaperBtn.clicked.connect(PCMember.close)
        ###
        self.papersToBidList.itemClicked.connect(self.showPaperContent) ###Inserts paper content into textbox
        self.submitBtn.clicked.connect(self.submitPaperBid)


        ###GO TO REVIEWING PROCESS POP UP
        self.viewReviewingProcessBtn.clicked.connect(self.openReviewingProcessPopUp)
        ###
        QtCore.QMetaObject.connectSlotsByName(PCMember)
        paper_list = Service().paperListCheck()
        for paper in paper_list:

            item = QListWidgetItem(str(paper.paperID) + ') ' + paper.name)
            item.setData(1, paper)
            self.papersToBidList.addItem(item)
        ###



    def retranslateUi(self, PCMember):
        _translate = QtCore.QCoreApplication.translate
        PCMember.setWindowTitle(_translate("PCMember", "PC member"))
        self.submitBtn.setText(_translate("PCMember", "Submit"))
        self.label_2.setText(_translate("PCMember", "Paper text"))
        self.label.setText(_translate("PCMember", "Paper list"))
        self.biding_bidingBtn.setText(_translate("PCMember", "Biding"))
        self.biding_assignReviewsBtn.setText(_translate("PCMember", "Assign Reviews"))
        self.biding_nonConclusiveReviewsBtn.setText(_translate("PCMember", "Non-Conclusive Reviews"))
        self.biding_changeDeadlinesBtn.setText(_translate("PCMember", "Change Deadlines"))
        self.biding_chooseSectionToSuperviseBtn.setText(_translate("PCMember", "Choose Section to Supervise"))
        self.biding_viewAssignedPapersBtn.setText(_translate("PCMember", "View Assigned Papers"))
        self.biding_viewYourPaperBtn.setText(_translate("PCMember", "View your Paper"))
        self.bidding_ErrorMessageLabel.setText(_translate("PCMember", ""))
        self.assignReviews_bidingBtn.setText(_translate("PCMember", "Biding"))
        self.assignReviews_assignReviewsBtn.setText(_translate("PCMember", "Assign Reviewers"))
        self.assignReviews_nonConclusiveReviewsBtn.setText(_translate("PCMember", "Non-Conclusive Reviews"))
        self.assignReviews_changeDeadlinesBtn.setText(_translate("PCMember", "Change Deadlines"))
        self.assignReviews_chooseSectionToSuperviseBtn.setText(_translate("PCMember", "Choose Section to Supervise"))
        self.assignReviews_viewAssignedPapersBtn.setText(_translate("PCMember", "View Assigned Papers"))
        self.assignReviews_viewYourPaperBtn.setText(_translate("PCMember", "View your Paper"))
        self.clearBtn.setText(_translate("PCMember", "Clear"))
        self.viewReviewingProcessBtn.setText(_translate("PCMember", "View Papers in Reviewing Process"))
        self.assignPaperBtn.setText(_translate("PCMember", "Assign Paper"))
        self.requestReconsiderationBtn.setText(_translate("PCMember", "Request Reconsideration"))
        self.label_3.setText(_translate("PCMember", "Reviewers"))
        self.label_4.setText(_translate("PCMember", "Paper"))
        self.assignNewReviewerBtn.setText(_translate("PCMember", "Assign new Reviewers"))
        self.label_5.setText(_translate("PCMember", "Paper Content"))
        self.acceptPaperBtn.setText(_translate("PCMember", "Accept Paper"))
        self.rejectPaperBtn.setText(_translate("PCMember", "Reject Paper"))
        self.addReviewerBtn.setText(_translate("PCMember", "Add Reviewer"))
        self.nonConclusive_bidingBtn.setText(_translate("PCMember", "Biding"))
        self.nonConclusive_assignReviewsBtn.setText(_translate("PCMember", "Assign Reviews"))
        self.nonConclusive_nonConclusiveReviewsBtn.setText(_translate("PCMember", "Non-Conclusive Reviews"))
        self.nonConclusive_changeDeadlinesBtn.setText(_translate("PCMember", "Change Deadlines"))
        self.nonConclusive_chooseSectionToSuperviseBtn.setText(_translate("PCMember", "Choose Section to Supervise"))
        self.nonConclusive_viewAssignedPapersBtn.setText(_translate("PCMember", "View Assigned Papers"))
        self.nonConclusive_viewYourPaperBtn.setText(_translate("PCMember", "View your Paper"))
        self.label_6.setText(_translate("PCMember", "Review deadline"))
        self.updateConfirmationLabel.setText(_translate("PCMember", "<update status>"))
        self.pushButton.setText(_translate("PCMember", "Update Dates"))
        self.changeDeadlines_bidingBtn.setText(_translate("PCMember", "Biding"))
        self.changeDeadlines_assignReviewsBtn.setText(_translate("PCMember", "Assign Reviews"))
        self.changeDeadlines_nonConclusiveReviewsBtn.setText(_translate("PCMember", "Non-Conclusive Reviews"))
        self.changeDeadlines_changeDeadlinesBtn.setText(_translate("PCMember", "Change Deadlines"))
        self.changeDeadlines_chooseSectionToSuperviseBtn.setText(_translate("PCMember", "Choose Section to Supervise"))
        self.changeDeadlines_viewAssignedPapersBtn.setText(_translate("PCMember", "View Assigned Papers"))
        self.changeDeadlines_viewYourPaperBtn.setText(_translate("PCMember", "View your Paper"))
        self.label_7.setText(_translate("PCMember", "Bidding deadline"))
        self.label_8.setText(_translate("PCMember", "Document upload deadline"))
        self.label_9.setText(_translate("PCMember", "Abstract upload deadline"))
        self.updateBtn.setText(_translate("PCMember", "Update"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PCMember", "Section"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PCMember", "Speaker"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PCMember", "Paper title/topic"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PCMember", "Supervisor"))
        self.sectionToSupervise_bidingBtn.setText(_translate("PCMember", "Biding"))
        self.sectionToSupervise_assignReviewsBtn.setText(_translate("PCMember", "Assign Reviews"))
        self.sectionToSupervise_nonConclusiveReviewsBtn.setText(_translate("PCMember", "Non-Conclusive Reviews"))
        self.sectionToSupervise_changeDeadlinesBtn.setText(_translate("PCMember", "Change Deadlines"))
        self.sectionToSupervise_chooseSectionToSuperviseBtn.setText(_translate("PCMember", "Choose Section to Supervise"))
        self.sectionToSupervise_viewAssignedPapersBtn.setText(_translate("PCMember", "View Assigned Papers"))
        self.sectionToSupervise_viewYourPaperBtn.setText(_translate("PCMember", "View your Paper"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PCMember = QtWidgets.QStackedWidget()
    ui = Ui_PCMember()
    ui.setupUi(PCMember, UserType(False, False, True, 'user1'))
    PCMember.show()
    sys.exit(app.exec_())

