
from PyQt5 import QtCore, QtWidgets
from UI.ReviewerResults import Ui_ReviewerResults


class Ui_ReviewerReviews(object):
    def openReviewerResultsWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ReviewerResults()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, ReviewerReviews):
        ReviewerReviews.setObjectName("ReviewerReviews")
        ReviewerReviews.resize(1024, 720)
        self.centralwidget = QtWidgets.QWidget(ReviewerReviews)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 180, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.buttonsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.yourReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.yourReviewsBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yourReviewsBtn.sizePolicy().hasHeightForWidth())
        self.yourReviewsBtn.setSizePolicy(sizePolicy)
        self.yourReviewsBtn.setMaximumSize(QtCore.QSize(400, 50))
        self.yourReviewsBtn.setObjectName("yourReviewsBtn")
        self.buttonsLayout.addWidget(self.yourReviewsBtn)
        self.otherReviewsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.otherReviewsBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.otherReviewsBtn.setObjectName("otherReviewsBtn")
        self.buttonsLayout.addWidget(self.otherReviewsBtn)
        self.paperList = QtWidgets.QListWidget(self.centralwidget)
        self.paperList.setGeometry(QtCore.QRect(200, 49, 256, 601))
        self.paperList.setObjectName("paperList")
        self.paperAbstractList = QtWidgets.QListWidget(self.centralwidget)
        self.paperAbstractList.setGeometry(QtCore.QRect(470, 50, 270, 271))
        self.paperAbstractList.setObjectName("paperAbstractList")
        self.feedbackList = QtWidgets.QListWidget(self.centralwidget)
        self.feedbackList.setGeometry(QtCore.QRect(470, 360, 540, 290))
        self.feedbackList.setObjectName("feedbackList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 120, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 20, 120, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 340, 140, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(760, 20, 120, 30))
        self.label_4.setObjectName("label_4")
        self.gradeBox = QtWidgets.QComboBox(self.centralwidget)
        self.gradeBox.setGeometry(QtCore.QRect(760, 50, 210, 30))
        self.gradeBox.setEditable(False)
        self.gradeBox.setObjectName("gradeBox")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.gradeBox.addItem("")
        self.submitReviewBtn = QtWidgets.QPushButton(self.centralwidget)
        self.submitReviewBtn.setGeometry(QtCore.QRect(760, 240, 111, 41))
        self.submitReviewBtn.setObjectName("submitReviewBtn")
        self.downloadDocBtn = QtWidgets.QPushButton(self.centralwidget)
        self.downloadDocBtn.setGeometry(QtCore.QRect(760, 300, 111, 41))
        self.downloadDocBtn.setObjectName("downloadDocBtn")
        ReviewerReviews.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReviewerReviews)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        ReviewerReviews.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReviewerReviews)
        self.statusbar.setObjectName("statusbar")
        ReviewerReviews.setStatusBar(self.statusbar)

        self.retranslateUi(ReviewerReviews)
        self.otherReviewsBtn.clicked.connect(self.openReviewerResultsWindow)
        self.otherReviewsBtn.clicked.connect(ReviewerReviews.close)
        QtCore.QMetaObject.connectSlotsByName(ReviewerReviews)

    def retranslateUi(self, ReviewerReviews):
        _translate = QtCore.QCoreApplication.translate
        ReviewerReviews.setWindowTitle(_translate("ReviewerReviews", "Reviewer"))
        self.yourReviewsBtn.setText(_translate("ReviewerReviews", "Your reviews"))
        self.otherReviewsBtn.setText(_translate("ReviewerReviews", "Other reviews"))
        self.label.setText(_translate("ReviewerReviews", "Papers to review"))
        self.label_2.setText(_translate("ReviewerReviews", "Paper abstract"))
        self.label_3.setText(_translate("ReviewerReviews", "Feedback editor"))
        self.label_4.setText(_translate("ReviewerReviews", "Select grade:"))
        self.gradeBox.setCurrentText(_translate("ReviewerReviews", "[Select a grade]"))
        self.gradeBox.setItemText(0, _translate("ReviewerReviews", "[Select a grade]"))
        self.gradeBox.setItemText(1, _translate("ReviewerReviews", "Strong accept"))
        self.gradeBox.setItemText(2, _translate("ReviewerReviews", "Accept"))
        self.gradeBox.setItemText(3, _translate("ReviewerReviews", "Weak accept"))
        self.gradeBox.setItemText(4, _translate("ReviewerReviews", "Borderline"))
        self.gradeBox.setItemText(5, _translate("ReviewerReviews", "Weak reject"))
        self.gradeBox.setItemText(6, _translate("ReviewerReviews", "Reject"))
        self.gradeBox.setItemText(7, _translate("ReviewerReviews", "Strong reject"))
        self.submitReviewBtn.setText(_translate("ReviewerReviews", "Submit review"))
        self.downloadDocBtn.setText(_translate("ReviewerReviews", "Download doc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReviewerReviews = QtWidgets.QMainWindow()
    ui = Ui_ReviewerReviews()
    ui.setupUi(ReviewerReviews)
    ReviewerReviews.show()
    sys.exit(app.exec_())
